### ISSUE TITLE
Client fails on xml.parsers.expat.ExpatError

### ISSUE THREAD

**Issue by ksomervi** [maxcutler/python-wordpress-xmlrpc#108]
Hello,
I've got a script that uploads images to a wordpress site and recently started getting this error. It seems to be an issue with the xmlrpc library. Any suggestions?

Traceback (most recent call last):
  File "/home/ksomervi/src/sift/sift.py", line 234, in <module>
    client = Client(url, user, passwd)
  File "/usr/lib/python3.5/site-packages/wordpress_xmlrpc/base.py", line 24, in __init__
    self.supported_methods = self.server.mt.supportedMethods()
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 1320, in parse_response
    p.close()
  File "/usr/lib64/python3.5/xmlrpc/client.py", line 447, in close
    parser.Parse(b"", True) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

This code has been working for a while and just recently stopped working. Any suggestions as to where to look.
Thanks.

**Comment by ksomervi** [comment]
My bad. Another plugin was causing the issue.
