### ISSUE TITLE
 Solve “500 Internal Server Error”

### ISSUE THREAD

**Issue by xiaoxixiaoxi** [maxcutler/python-wordpress-xmlrpc#119]
Solve
I tried to post articles via python but there are errors why
Can help me, thank you
Error message:

Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/爬虫学习/wordpress.py", line 17, in <module>
    client.call(NewPost(post))
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/wordpress_xmlrpc/base.py", line 37, in call
    raw_result = server_method(*args)
  File "/Users/apple/anaconda3/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/Users/apple/anaconda3/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/Users/apple/anaconda3/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Users/apple/anaconda3/lib/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for www.地址.com/xmlrpc.php: 500 Internal Server Error>

**Comment by maxcutler** [comment]
A 500 error is being returned from your server. You'll have to check your server logs to understand what the issue is, it's impossible to diagnose from the client library.
