### ISSUE TITLE
Inplace post edits are returning Fault 404: 'Invalid attachment ID.'

### ISSUE THREAD

**Issue by felciano** [maxcutler/python-wordpress-xmlrpc#29]
I am trying to use your library (v2.1) to write a script to replace broken links after a blog migration to Wordpress.com. After retrieving posts and making corrections to the post.body, I 

```
if not(wp.call(EditPost(post.id, post))):
    logging.error("Unable to edit post %s" % (post.id))
else:
    logging.info("Successfully updated post %s" % (post.id))
```

Running this consistently yields this error, irrespective of the post in question or whether any changes were made:

``````
Traceback (most recent call last):
  File "wplinkrepair.py", line 260, in <module>
    fix_errors=args.repair)
  File "wplinkrepair.py", line 206, in process_broken_links
    if not(wp.call(EditPost(post.id, post))):
  File "C:\Python27\lib\site-packages\wordpress_xmlrpc\base.py", line 37, in call
    raw_result = server_method(*args)
  File "C:\Python27\lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1575, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "C:\Python27\lib\xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "C:\Python27\lib\xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0]) 
xmlrpclib.Fault: <Fault 404: 'Invalid attachment ID.'>```
``````

Any suggestions?

**Comment by zodman** [comment]
+1 to fix from the code!

**Comment by swanithakvn** [comment]
Thank you! using post.thumbnail = post.thumbnail['attachment_id'] helped!!

**Comment by netcharger** [comment]
Thank You so much 
 
 this worked for me 

 post.thumbnail = post.thumbnail['attachment_id'] 


Thanks Lot
